### ISSUE TITLE
how do i open the gui?

### ISSUE THREAD

**Issue by joaoshiozo** [ionar2/Wurst-Blue#7]
i tried everything but i cant open the gui

**Comment by r-33** [comment]
press the command button. *pictured below*
![image](https://user-images.githubusercontent.com/65020937/86882236-19e0ad80-c12f-11ea-82a7-e57b08db6707.png)

**Comment by Jumpinqq** [comment]
high quality image

**Comment by joaoshiozo** [comment]
imma test it real quick
